### ISSUE TITLE
Drop to buffer if trigger space fe out of a repo?

### ISSUE THREAD

**Issue by tmpm697** [habamax/.vim#5]
Step:
1. open vim9 in a path that not in a git repo (folder that contains .git/)
2. trigger space fe
3. type smth, you're now drop to buffer and ctrl-c multiple also won't help you to exit, need to wait for vim9 a while before it echo message that you can exit by :qa!

**Comment by habamax** [comment]
![vim-fe](https://user-images.githubusercontent.com/234774/210315812-d0aedd6f-5b2f-4415-bcd3-cd97623522ba.gif)

can't reproduce

**Comment by tmpm697** [comment]
Ok i can see the problem here.
vi .vimrc
```
# add this line to .vimrc
execute 'nnoremap \. :edit' resolve(expand('~/.vimrc')) '<CR>'
```

steps:
1. cd to folder out of git repo
2. vim
3. press \\. to trigger above command
4. press space fe --> now you're drop to buffer

**Comment by habamax** [comment]
Okay, it is a known thing. Basically you try to search your home directory with all subdirectories it has. When there are too many files, it doesn't work too great, compared to fzf or my other plugin vim-select.

This implementation is simple, it doesn't use jobs to have a non-blocking filesystem scan.

For me it works pretty much ok, but I almost never do a fuzzy search against directories that have more than 50K files.

I don't want to make it non-blocking :)

**Comment by tmpm697** [comment]
I will trade it (async) for correctly displaying window size/position when popup window came out like your approach.
I like the UI, window's border and how search input displayed rounded by window's border.
Perfect for my taste but jeez, I can't back to vim due to [this](https://github.com/vim/vim/issues/5157) and scroll flick in vim that I can't bear.

**Comment by habamax** [comment]
The clipboard workaround I use for wayland (for foot, but it should also work for alacritty): https://github.com/habamax/.vim/blob/master/plugin/foot.vim

It relies on `wl-paste` and `wl-copy` external utilities.

**Comment by tmpm697** [comment]
I never use `"+p` to yank, the workaround solution seems adhere with `"`, but I often do `yy` to yank line to system clipboard that your workaround won't work.

**Comment by habamax** [comment]
Works for me, it is there in the script, depends on the clipboard setting

**Comment by habamax** [comment]
https://github.com/habamax/.vim/blob/d27a912be60fb5a8accd0964690b7c0667cb4c89/plugin/foot.vim#L9

**Comment by tmpm697** [comment]
i had this in .vimrc: `nnoremap yy :call WLYank(v:event)<cr>` should It invoke wl-copy when doing yy? it echos `E117: Unknown function: WLYank` -- should I load it somewhere?

**Comment by habamax** [comment]
Well, it is in the script and it works a bit different. 
In short, there is an autocommand that should onvoke that function.

**Comment by tmpm697** [comment]
the default of your .vim config, visual select text and then press `y` won't yank anything to system clipboard. have you tested it?

**Comment by habamax** [comment]
As I said, depends on the clipboard setting. It is clearly visible in the script source. If I turn it on amd restar vim in foot terminal - it works.

There is also a guard - it only is enabled for foot term.
