### ISSUE TITLE
space fp always keep at folder that start vim?

### ISSUE THREAD

**Issue by tmpm697** [habamax/.vim#6]
the last commit not fix this issue but broke the feature: c93b43e5758b9b2a480e9a07c6ee6dcffb62d81e
the path in `project.json` must not have `/` at start of it, i.e: `[{"path":"home/user/a/folder"}]`, c93b43e5758b9b2a480e9a07c6ee6dcffb62d81e add / at start of `home` then broke it.

put the last commit issue aside, if we have correct path in project.json like 
```
[{"path":"home/user/a/folder"}, {"path":"home/user/another/folder"}, {"path":"/tmp/a/folder"}]
```

steps:
1. cd /home/user/a
2. vim
3. space fp and select /tmp/a/folder--> show every files under home/user/a
4. exit vim and cd to /tmp/a
5. vim 
6. space fp and select home/user/a/folder --> show every files under /tmp/a

**Comment by habamax** [comment]
It didn't break anything for me, but fixed an issue I overlooked while used vim on windows where there is no `/paths/like/this`.

In your case, when the path is non existent, it fallbacks to a current working directory -- the one you were in when launched vim (relates to 6 in you message).

In other words, can't reproduce:
![vim-fp-2](https://user-images.githubusercontent.com/234774/210450408-d20ea27e-4629-4eb0-a1a8-ed7d3e73a744.gif)
